packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@eslint/compat': 1.2.8
  '@eslint/eslintrc': 3.3.1
  '@eslint/js': 9.25.1
  '@heroui/button': 2.2.27
  '@heroui/code': 2.2.21
  '@heroui/dropdown': 2.3.27
  '@heroui/input': 2.4.28
  '@heroui/kbd': 2.2.22
  '@heroui/link': 2.2.23
  '@heroui/navbar': 2.2.25
  '@heroui/snippet': 2.2.28
  '@heroui/switch': 2.2.24
  '@heroui/system': 2.4.23
  '@heroui/theme': 2.4.23
  '@heroui/use-theme': 2.1.10
  '@nx/eslint': 21.5.2
  '@nx/vite': 21.5.2
  '@prettier/plugin-xml': ^3.4.2
  '@react-aria/visually-hidden': 3.8.28
  '@react-types/shared': 3.32.1
  '@tailwindcss/postcss': 4.1.11
  '@tailwindcss/vite': 4.1.11
  '@types/node': 20.5.7
  '@types/react': 18.3.3
  '@types/react-dom': 18.3.0
  '@typescript-eslint/eslint-plugin': 8.31.1
  '@typescript-eslint/parser': 8.31.1
  '@vitejs/plugin-react': 4.7.0
  bumpp: ^10.3.1
  clsx: 2.1.1
  cz-git: ^1.12.0
  dotenv: ^17.2.3
  eslint-config-prettier: 9.1.0
  eslint-plugin-format: ^1.0.2
  eslint-plugin-import: 2.31.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-node: 11.1.0
  eslint-plugin-prettier: 5.2.1
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-unused-imports: 4.1.4
  framer-motion: 11.18.2
  globals: 16.0.0
  husky: ^9.1.7
  lint-staged: ^16.2.6
  nx: 21.5.2
  postcss: 8.5.6
  prettier: 3.5.3
  prettier-plugin-tailwindcss: ^0.6.14
  react: 18.3.1
  react-dom: 18.3.1
  react-router-dom: 6.23.0
  tailwind-variants: 3.1.1
  tailwindcss: 4.1.11
  typescript: 5.6.3
  vite: 6.0.11
  vite-tsconfig-paths: 5.1.4
  vitest: ^3.2.4

cleanupUnusedCatalogs: true

engineStrict: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

injectWorkspacePackages: true

nodeVersion: 22.17.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - sharp
  - nx

saveExact: true

shamefullyHoist: true

syncInjectedDepsAfterScripts:
  - build
