name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - deploy
    paths-ignore:
      - infra/**
      - docs/**
      - scripts/**
      - .vscode/**
      - .github/archive/**
      - .github/instructions/**
      - '**/tests?/**'

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
      SUPABASE_DIRECT_URL: ${{ secrets.SUPABASE_DIRECT_URL }}
      SUPABASE_SECRET_API_KEY: ${{ secrets.SUPABASE_SECRET_API_KEY }}
      SUPABASE_PUBLIC_API_KEY: ${{ secrets.SUPABASE_PUBLIC_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v5
        name: Install Node.js
        with:
          node-version: '>=22'
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13.0

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install ansible-core
          ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3.13.0
        run: |
          ansible-playbook -i ansible/inventory/local.yml ansible/deploy-api.yml
